### ISSUE TITLE
IndexError: list index out of range on Windows 10

### ISSUE THREAD

**Issue by Rabia-Noureen** [glample/tagger#62]
Hi @glample i am new to python and i wanted to use this system but while training the model on windows 10 i got the following error. I tried to replace the 2 lines in utils.py in order to avoid path related issues but the error remains the same. Please guide me how i can avoid the error. This issue has also been mentioned in https://github.com/glample/tagger/issues/54.
```
models_path = u"\\\\?\\" + os.path.abspath(u".\\models")
eval_path =  u"\\\\?\\" + os.path.abspath(u".\\evaluation")
```

```
run train.py --train dataset/eng.train --dev dataset/eng.testa --test dataset/eng.testb
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GT 620M (CNMeM is enabled with initial size: 85.0% of memory, cuDNN not available)
Model location: ./models
Found 23624 unique words (203621 in total)
Found 84 unique characters
Found 17 unique named entity tags
14041 / 3250 / 3453 sentences in train / dev / test.
Saving the mappings to disk...
Compiling...
Starting epoch 0...
50, cost average: 18.960564
100, cost average: 10.907215
150, cost average: 12.533095
200, cost average: 10.245933
250, cost average: 13.977984
300, cost average: 14.902864
350, cost average: 13.581712
400, cost average: 14.167278
450, cost average: 12.335945
500, cost average: 11.382500
550, cost average: 12.137071
600, cost average: 10.413382
650, cost average: 11.004699
700, cost average: 7.299953
750, cost average: 11.655169
800, cost average: 12.359253
850, cost average: 10.576831
900, cost average: 9.708168
950, cost average: 10.565039
ID     NE  Total      O  S-LOC  B-PER  E-PER  S-ORG S-MISC  B-ORG  E-ORG  S-PER  I-ORG  B-LOC  E-LOC B-MISC E-MISC I-MISC  I-PER  I-LOC  Percent
 0      O  42759  42759      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0  100.000
 1  S-LOC   1603   1603      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 2  B-PER   1234   1234      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 3  E-PER   1234   1234      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 4  S-ORG    891    891      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 5 S-MISC    665    665      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 6  B-ORG    450    450      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 7  E-ORG    450    450      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 8  S-PER    608    608      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 9  I-ORG    301    301      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
10  B-LOC    234    234      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
11  E-LOC    234    234      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
12 B-MISC    257    257      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
13 E-MISC    257    257      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
14 I-MISC     89     89      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
15  I-PER     73     73      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
16  I-LOC     23     23      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
42759/51362 (83.25026%)
Traceback (most recent call last):

  File "C:\Users\Acer\tagger-master\train.py", line 220, in <module>
    dev_data, id_to_tag, dico_tags)

  File "utils.py", line 282, in evaluate
    return float(eval_lines[1].strip().split()[-1])

IndexError: list index out of range
```

**Comment by PCR11** [comment]
hello,i have the same question with you,did yo solve it?
