### ISSUE TITLE
IOError "No such file or directory: './evaluation/temp/eval.1181043.scores "

### ISSUE THREAD

**Issue by Daisy-123** [glample/tagger#78]
Hi 
I tried this code " **time /tools/anaconda2/bin/python train.py --train dataset/train1400.iob --dev dataset/dev300.iob --test dataset/test284.iob --tag_scheme iob >  test-output0611** "
, but I  got the error message " **IOError: [Errno 2] No such file or directory: './evaluation/temp/eval.1181043.scores** "

How can I solve this problem ?

**Comment by glample** [comment]
What does the full log file contain?
Could you check this is not a problem with permissions and that the script is allowed to create this scores file in the temp directory? (Also, does the temp directory exist?)

**Comment by Daisy-123** [comment]
* Full log : 
**WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "train.py", line 222, in <module>
    test_data, id_to_tag, dico_tags)
  File "/mnt/Storage01/blue90211/tagger-master/utils.py", line 277, in evaluate
    eval_lines = [l.rstrip() for l in codecs.open(scores_path, 'r', 'utf8')]
  File "/tools/anaconda2/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: './evaluation/temp/eval.1181043.scores'**
* Temp directory is generated by script (not exited before).
* I got eval.1181043.output file in temp directory ,but I can't find eval.1181043.scores.
* The process seems on going ... as below (stopped in epoch 0) : 
"
**..............
27900, cost average: 0.028285
27950, cost average: 0.456446
processed 1307517 tokens with 3937 phrases; found: 324 phrases; correct: 192.
accuracy:  99.30%; precision:  59.26%; recall:   4.88%; FB1:   9.01
            Claim: precision:  59.26%; recall:  15.79%; FB1:  24.94  324
         PriorArt: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
ID     NE  Total      OI-ClaimB-PriorArtI-PriorArtB-Claim  Percent
 0      O12952511294615    583      0      0     53   99.951
 1I-Claim   6480   2950   3530      0      0      0   54.475
 2B-PriorArt   2721   2655     65      0      0      1    0.000
 3I-PriorArt   1849   1839     10      0      0      0    0.000
 4B-Claim   1216    922     24      0      0    270   22.204
1298415/1307517 (99.30387%)
processed 1133259 tokens with 4170 phrases; found: 302 phrases; correct: 171.
accuracy:  99.20%; precision:  56.62%; recall:   4.10%; FB1:   7.65
            Claim: precision:  56.90%; recall:  14.07%; FB1:  22.56  297
         PriorArt: precision:  40.00%; recall:   0.07%; FB1:   0.13  5
ID     NE  Total      OI-ClaimB-PriorArtI-PriorArtB-Claim  Percent
 0      O11213951120900    443      2      0     50   99.956
 1I-Claim   5686   2610   3074      0      0      2   54.063
 2B-PriorArt   2969   2906     58      2      0      3    0.067
 3I-PriorArt   2008   1981     24      1      0      2    0.000
 4B-Claim   1201    926     40      0      0    235   19.567
1124211/1133259 (99.20159%)
Score on dev: 9.01000
Score on test: 7.65000
New best score on dev.
Saving model to disk...
New best score on test.
28000, cost average: 0.016292
28050, cost average: 0.545872
28100, cost average: 0.665584
28150, cost average: 0.817216
28200, cost average: 0.029983
28250, cost average: 0.342566
28300, cost average: 0.429246
28350, cost average: 0.035073
28400, cost average: 0.009134
28450, cost average: 0.274903
28500, cost average: 0.448717
28550, cost average: 0.014378
28600, cost average: 0.342188
28650, cost average: 0.033076
28700, cost average: 0.010674
28750, cost average: 0.009748
28800, cost average: 0.018098
28850, cost average: 0.020268
28900, cost average: 0.022872
28950, cost average: 0.271496
processed 1307517 tokens with 3937 phrases; found: 534 phrases; correct: 30.
accuracy:  99.24%; precision:   5.62%; recall:   0.76%; FB1:   1.34
            Claim: precision:   5.62%; recall:   2.47%; FB1:   3.43  534
         PriorArt: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
ID     NE  Total      OI-ClaimB-PriorArtI-PriorArtB-Claim  Percent
 0      O12952511292716   2424      0      0    111   99.804
 1I-Claim   6480   1968   4509      0      0      3   69.583
 2B-PriorArt   2721   2324    370      0      0     27    0.000
 3I-PriorArt   1849   1702    137      0      0     10    0.000
 4B-Claim   1216    749     88      0      0    379   31.168
1297604/1307517 (99.24185%)
....................**
"

**Comment by junchenzhi** [comment]
> * Full log :
>   **WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
>   Traceback (most recent call last):
>   File "train.py", line 222, in 
>   test_data, id_to_tag, dico_tags)
>   File "/mnt/Storage01/blue90211/tagger-master/utils.py", line 277, in evaluate
>   eval_lines = [l.rstrip() for l in codecs.open(scores_path, 'r', 'utf8')]
>   File "/tools/anaconda2/lib/python2.7/codecs.py", line 896, in open
>   file = **builtin**.open(filename, mode, buffering)
>   IOError: [Errno 2] No such file or directory: './evaluation/temp/eval.1181043.scores'**
> * Temp directory is generated by script (not exited before).
> * I got eval.1181043.output file in temp directory ,but I can't find eval.1181043.scores.
> * The process seems on going ... as below (stopped in epoch 0) :
>   "
>   **..............
>   27900, cost average: 0.028285
>   27950, cost average: 0.456446
>   processed 1307517 tokens with 3937 phrases; found: 324 phrases; correct: 192.
>   accuracy:  99.30%; precision:  59.26%; recall:   4.88%; FB1:   9.01
>   Claim: precision:  59.26%; recall:  15.79%; FB1:  24.94  324
>   PriorArt: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
>   ID     NE  Total      OI-ClaimB-PriorArtI-PriorArtB-Claim  Percent
>   0      O12952511294615    583      0      0     53   99.951
>   1I-Claim   6480   2950   3530      0      0      0   54.475
>   2B-PriorArt   2721   2655     65      0      0      1    0.000
>   3I-PriorArt   1849   1839     10      0      0      0    0.000
>   4B-Claim   1216    922     24      0      0    270   22.204
>   1298415/1307517 (99.30387%)
>   processed 1133259 tokens with 4170 phrases; found: 302 phrases; correct: 171.
>   accuracy:  99.20%; precision:  56.62%; recall:   4.10%; FB1:   7.65
>   Claim: precision:  56.90%; recall:  14.07%; FB1:  22.56  297
>   PriorArt: precision:  40.00%; recall:   0.07%; FB1:   0.13  5
>   ID     NE  Total      OI-ClaimB-PriorArtI-PriorArtB-Claim  Percent
>   0      O11213951120900    443      2      0     50   99.956
>   1I-Claim   5686   2610   3074      0      0      2   54.063
>   2B-PriorArt   2969   2906     58      2      0      3    0.067
>   3I-PriorArt   2008   1981     24      1      0      2    0.000
>   4B-Claim   1201    926     40      0      0    235   19.567
>   1124211/1133259 (99.20159%)
>   Score on dev: 9.01000
>   Score on test: 7.65000
>   New best score on dev.
>   Saving model to disk...
>   New best score on test.
>   28000, cost average: 0.016292
>   28050, cost average: 0.545872
>   28100, cost average: 0.665584
>   28150, cost average: 0.817216
>   28200, cost average: 0.029983
>   28250, cost average: 0.342566
>   28300, cost average: 0.429246
>   28350, cost average: 0.035073
>   28400, cost average: 0.009134
>   28450, cost average: 0.274903
>   28500, cost average: 0.448717
>   28550, cost average: 0.014378
>   28600, cost average: 0.342188
>   28650, cost average: 0.033076
>   28700, cost average: 0.010674
>   28750, cost average: 0.009748
>   28800, cost average: 0.018098
>   28850, cost average: 0.020268
>   28900, cost average: 0.022872
>   28950, cost average: 0.271496
>   processed 1307517 tokens with 3937 phrases; found: 534 phrases; correct: 30.
>   accuracy:  99.24%; precision:   5.62%; recall:   0.76%; FB1:   1.34
>   Claim: precision:   5.62%; recall:   2.47%; FB1:   3.43  534
>   PriorArt: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
>   ID     NE  Total      OI-ClaimB-PriorArtI-PriorArtB-Claim  Percent
>   0      O12952511292716   2424      0      0    111   99.804
>   1I-Claim   6480   1968   4509      0      0      3   69.583
>   2B-PriorArt   2721   2324    370      0      0     27    0.000
>   3I-PriorArt   1849   1702    137      0      0     10    0.000
>   4B-Claim   1216    749     88      0      0    379   31.168
>   1297604/1307517 (99.24185%)
>   ....................**
>   "

Hi,  I have the same bug.  Have you solved it? How did you solve it? Thanks~
